language: csharp
mono: none
dist: xenial
dotnet: 3.1
env:
  global:
    - PACKAGE_VERSION="$MAJOR_VERSION_NUMBER.$MINOR_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER"

script:
  - dotnet restore
  - dotnet build
  - cd ./AStar.Tests
  - dotnet test
  - cd ../AStar

stages:
  - build
  - test
  - package

jobs:
  include:
    - stage: build
      script:
        - dotnet restore
        - dotnet build
    - stage: test
      script:
        - cd ./AStar.Tests
        - dotnet test
    - stage: package
      if: branch = "development"
      script:
        - cd ../AStar
        - dotnet pack -c Release /p:PackageVersion=$PACKAGE_VERSION-alpha
        # - dotnet nuget push ./bin/Release/AStarLite.$PACKAGE_VERSION.nupkg -s https://www.nuget.org/api/v2/package -k $NUGET_API_KEY
