language: csharp
mono: none
dist: xenial
dotnet: 3.1
os: linux
env:
  global:
    - PACKAGE_VERSION_RELEASE="1.0.0-beta.$TRAVIS_BUILD_NUMBER"
    - PACKAGE_VERSION_PRERELEASE="1.0.1-alpha.$TRAVIS_BUILD_NUMBER"

script:
  - dotnet restore
  - dotnet build
  - cd ./AStar.Tests
  - dotnet test

stages:
  - build and test
  - package prerelease
  - package release

jobs:
  include:
    - stage: build and test
      script:
        - dotnet restore
        - dotnet build
        - cd ./AStar.Tests
        - dotnet test
    - stage: package prerelease
      if: branch = "development" AND env(TRAVIS_PULL_REQUEST) = false
      script:
        - cd ../AStar
        - dotnet pack -c Release /p:PackageVersion=$PACKAGE_VERSION_PRERELEASE
        - dotnet nuget push ./bin/Release/AStarLite.PACKAGE_VERSION_PRERELEASE.nupkg -s https://www.nuget.org/api/v2/package -k $NUGET_API_KEY
    - stage: package release
      if: branch = "master" AND env(TRAVIS_PULL_REQUEST) = false
      script:
        - cd ../AStar
        - dotnet pack -c Release /p:PackageVersion=$PACKAGE_VERSION_RELEASE
        - dotnet nuget push ./bin/Release/AStarLite.$PACKAGE_VERSION_RELEASE.nupkg -s https://www.nuget.org/api/v2/package -k $NUGET_API_KEY
