language: csharp
mono: none
dist: xenial
dotnet: 3.1
script: 
  - dotnet restore
  - dotnet build
  - cd ./AStar.Tests
  - dotnet test
  - cd ../AStar
  - dotnet pack -c Release /p:PackageVersion=$MAJOR_VERSION_NUMBER.$MINOR_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER$VERSION_SUFFIX
  - dotnet nuget push ./bin/Release/AStarLite.$MAJOR_VERSION_NUMBER.$MINOR_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER$VERSION_SUFFIX.nupkg -s https://www.nuget.org/api/v2/package -k $NUGET_API_KEY
