language: csharp
mono: none
dotnet: 2.1.502
stages:
  build
# script:
#  - dotnet restore
#  - dotnet build
#  - cd ./AStar.Tests
#  - dotnet test
#   - cd ../AStar.Core
  #- dotnet pack -c Release /p:PackageVersion=$MAJOR_VERSION_NUMBER.$MINOR_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER
  #- dotnet nuget push ./bin/Release/AStarLite.$MAJOR_VERSION_NUMBER.$MINOR_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER.nupkg -s https://www.nuget.org/api/v2/package -k $NUGET_API_KEY

jobs:
  include:
    - stage: build
      script: 
        - dotnet restore
        - dotnet build